apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  type: ClusterIP # default service type, actually no need to set here
  selector:
    app: synergychat-crawler # which pods to route traffic to
  ports:
    - protocol: TCP # allow us to use HTTP
      port: 80 # port the service will listen on
      targetPort: 8080 # port the pods are listening on
