apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: synergychat-api # which pods to route traffic to
  ports:
    - protocol: TCP # allow us to use HTTP
      port: 80 # port the service will listen on
      targetPort: 8080 # port the pods are listening on
      nodePort: 30080
